### ISSUE TITLE
Loading videos saved with RGB color mapping

### ISSUE THREAD

**Issue by bobfromjapan** [postpop/videoreader#2]
Hello!
I recently used this program, via `napari_video`.  This `videoreader` is very helpful for loading videos quickly!

When I loaded the video, I noticed that the color tone was wrong. It was apparently due to a common problem stemming from OpenCV's default color mapping.
So, I added the following code to Line 88 of the `videoreader.py` and the video was displayed with the desired colors.

`frame=cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)`

I feel that making changes to the distributed `videoreader` code in this way is not a desirable practice.
Is there a option to get `videoreader` to display colors correctly when loading videos that are saved with normal RGB color mapping?

I would appreciate it if you could let me know.

**Comment by postpop** [comment]
Hi bobfromjapan!

Thank you for pointing that out! We mainly us b/w videos so are not much affected by this and we just manually fix this for our color videos as you did. But I see that this is an issue for others using the napari-video plugin.

I see two possible solutions: Either adding your fix to videoreader directly or fixing this in napari-videos (by adding your code after [line 19 in napari_video.py](https://github.com/janclemenslab/napari-video/blob/bf9dc0fe9cd67756a44b09d3f9f56b1ca2f4493b/src/napari_video/napari_video.py#L19)).

I prefer the second solution (fix this in napari-videos) since that way videoreader is consistent with the behavior of opencv. What do you think? If you agree, feel free to open a pull request in the [napari-video repo](https://github.com/janclemenslab/napari-video).

**Comment by bobfromjapan** [comment]
I agree with your suggestion! Considering the purpose of videoreader.py, which is a standard OpenCV wrapper, I thought it would be better not to change it.

So I will submit a pull request to napari_video repository later. Thank you very much for your help!

**Comment by bobfromjapan** [comment]
Thank you for merging pull request!
